// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalSite.Server.Data;

#nullable disable

namespace DemoSite.Server.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20250319204116_Initial_Migration")]
    partial class Initial_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PersonalSite")
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientPortal.Server.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Appointment", "PersonalSite");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = "f2b75dde-ff5c-4c8f-8a44-5a7af46fc6d1",
                            Location = 0,
                            Note = "Dolor voluptate quia dolores delectus doloremque omnis voluptatem officia fuga.\nEos dolore a.\nDicta tempora corrupti omnis rerum est.\nSed vero magnam sequi eligendi est sapiente molestiae unde tempora.\nEt suscipit et aut.",
                            Time = new DateTime(2025, 1, 4, 3, 34, 9, 334, DateTimeKind.Unspecified).AddTicks(4410)
                        },
                        new
                        {
                            Id = 2,
                            ClientId = "21d2afc1-49fb-4e30-8ab1-8427709c9f2b",
                            Location = 0,
                            Note = "Corrupti molestias explicabo quia et.\nQuasi sed ipsum deleniti ipsa quibusdam vel ratione tempora.",
                            Time = new DateTime(2025, 6, 10, 23, 14, 25, 64, DateTimeKind.Unspecified).AddTicks(8616)
                        },
                        new
                        {
                            Id = 3,
                            ClientId = "3a02dbc3-09cf-4511-9d8f-c40cc78c6285",
                            Location = 0,
                            Note = "Consequatur amet aut incidunt molestias vero laboriosam ipsa reiciendis omnis. Delectus asperiores iste iusto. Similique ut alias odit repudiandae enim consequatur ut enim. Beatae dolores neque ut consequuntur nemo.",
                            Time = new DateTime(2025, 4, 26, 10, 32, 45, 453, DateTimeKind.Unspecified).AddTicks(9675)
                        },
                        new
                        {
                            Id = 4,
                            ClientId = "f2b75dde-ff5c-4c8f-8a44-5a7af46fc6d1",
                            Location = 0,
                            Note = "Ut et exercitationem aut et vero suscipit ut.",
                            Time = new DateTime(2025, 3, 18, 5, 11, 53, 268, DateTimeKind.Unspecified).AddTicks(5895)
                        },
                        new
                        {
                            Id = 5,
                            ClientId = "f2b75dde-ff5c-4c8f-8a44-5a7af46fc6d1",
                            Location = 0,
                            Note = "Omnis quam neque perspiciatis corrupti in vel.\nMinima quis molestiae voluptas et voluptas delectus fuga ab suscipit.",
                            Time = new DateTime(2025, 2, 9, 12, 34, 56, 137, DateTimeKind.Unspecified).AddTicks(4208)
                        },
                        new
                        {
                            Id = 6,
                            ClientId = "c21ae03e-c588-4605-94f0-0f8019c56299",
                            Location = 0,
                            Note = "Rerum consequuntur quae voluptatem optio quidem voluptatem voluptas unde eaque.\nVoluptatibus aut qui.\nProvident laboriosam perspiciatis necessitatibus et sit maiores quis incidunt.",
                            Time = new DateTime(2025, 4, 20, 0, 35, 44, 532, DateTimeKind.Unspecified).AddTicks(3021)
                        },
                        new
                        {
                            Id = 7,
                            ClientId = "df986608-2a74-4168-84a7-043934b89456",
                            Location = 0,
                            Note = "eaque",
                            Time = new DateTime(2025, 3, 13, 22, 26, 26, 402, DateTimeKind.Unspecified).AddTicks(3235)
                        },
                        new
                        {
                            Id = 8,
                            ClientId = "f2b75dde-ff5c-4c8f-8a44-5a7af46fc6d1",
                            Location = 0,
                            Note = "nemo",
                            Time = new DateTime(2025, 4, 25, 13, 30, 44, 647, DateTimeKind.Unspecified).AddTicks(6686)
                        },
                        new
                        {
                            Id = 9,
                            ClientId = "e5fba865-f5c4-47b5-aed2-5a46a186cb83",
                            Location = 0,
                            Note = "Hic facere enim et optio dolores est iure. Commodi quaerat perspiciatis voluptas possimus cum quia libero esse ipsum. Ipsum nemo veritatis sint. Dolores odit nostrum quo qui ducimus qui.",
                            Time = new DateTime(2025, 4, 3, 6, 49, 9, 280, DateTimeKind.Unspecified).AddTicks(7843)
                        },
                        new
                        {
                            Id = 10,
                            ClientId = "f2b75dde-ff5c-4c8f-8a44-5a7af46fc6d1",
                            Location = 0,
                            Note = "Vero odit sit praesentium corporis voluptates et quas a. Hic et sapiente qui qui. Quae veniam consequuntur aut iste corrupti quae eum optio. Aspernatur libero blanditiis.",
                            Time = new DateTime(2025, 5, 12, 4, 37, 1, 145, DateTimeKind.Unspecified).AddTicks(5760)
                        },
                        new
                        {
                            Id = 11,
                            ClientId = "f2b75dde-ff5c-4c8f-8a44-5a7af46fc6d1",
                            Location = 0,
                            Note = "Animi ut dolorum id nemo dolorem aut.\nEst velit a velit consequatur distinctio sunt.\nMinus sunt repellendus labore eum delectus sed consequuntur.\nEligendi id consectetur non velit quo reprehenderit nisi dolore.\nMolestias rerum deleniti aliquid porro.",
                            Time = new DateTime(2025, 4, 6, 21, 29, 57, 130, DateTimeKind.Unspecified).AddTicks(7300)
                        },
                        new
                        {
                            Id = 12,
                            ClientId = "9e942e34-9563-447a-a12b-e6cb31f25f3a",
                            Location = 0,
                            Note = "Tempora modi illum.\nAut sit suscipit quasi deserunt recusandae aliquid nihil deserunt perferendis.\nInventore eveniet voluptas eveniet voluptatem et consequatur veniam et.\nQuia rerum modi atque rerum quos.",
                            Time = new DateTime(2025, 1, 21, 14, 22, 8, 996, DateTimeKind.Unspecified).AddTicks(5723)
                        },
                        new
                        {
                            Id = 13,
                            ClientId = "79ab798a-f0da-45de-958c-4f88a3c1d3aa",
                            Location = 0,
                            Note = "Sapiente dolorem quia eum libero.\nAut nostrum hic.\nAb odio et voluptatem commodi libero voluptate omnis.",
                            Time = new DateTime(2025, 6, 11, 17, 20, 58, 697, DateTimeKind.Unspecified).AddTicks(6214)
                        },
                        new
                        {
                            Id = 14,
                            ClientId = "3a02dbc3-09cf-4511-9d8f-c40cc78c6285",
                            Location = 0,
                            Note = "Eos odio iste nulla facilis consequatur rerum id.\nConsequuntur corrupti nobis porro.",
                            Time = new DateTime(2025, 3, 17, 23, 38, 5, 720, DateTimeKind.Unspecified).AddTicks(6672)
                        },
                        new
                        {
                            Id = 15,
                            ClientId = "df986608-2a74-4168-84a7-043934b89456",
                            Location = 0,
                            Note = "Non quia ad exercitationem laboriosam saepe.",
                            Time = new DateTime(2025, 4, 18, 1, 11, 17, 458, DateTimeKind.Unspecified).AddTicks(7441)
                        },
                        new
                        {
                            Id = 16,
                            ClientId = "21d2afc1-49fb-4e30-8ab1-8427709c9f2b",
                            Location = 0,
                            Note = "possimus",
                            Time = new DateTime(2025, 5, 12, 5, 19, 45, 718, DateTimeKind.Unspecified).AddTicks(2907)
                        },
                        new
                        {
                            Id = 17,
                            ClientId = "e5fba865-f5c4-47b5-aed2-5a46a186cb83",
                            Location = 0,
                            Note = "Distinctio id cupiditate qui nemo quos animi voluptatibus.\nEsse minus vitae cupiditate voluptatem iusto tempore officia eum.\nQuod animi aut error pariatur.\nArchitecto iure est.\nReprehenderit nobis hic aut iste dolores dicta magni.\nEveniet laborum rerum aperiam vel eum excepturi voluptate.",
                            Time = new DateTime(2025, 2, 5, 21, 17, 20, 601, DateTimeKind.Unspecified).AddTicks(6665)
                        },
                        new
                        {
                            Id = 18,
                            ClientId = "df986608-2a74-4168-84a7-043934b89456",
                            Location = 0,
                            Note = "Quas dicta consectetur.",
                            Time = new DateTime(2025, 6, 20, 12, 19, 44, 318, DateTimeKind.Unspecified).AddTicks(352)
                        },
                        new
                        {
                            Id = 19,
                            ClientId = "79ab798a-f0da-45de-958c-4f88a3c1d3aa",
                            Location = 0,
                            Note = "Et expedita animi. Sed facere et quis et consequuntur rerum voluptate quisquam omnis. Eum rem veritatis a velit fugiat eos hic eos nulla. Dolor ut non. Assumenda voluptatem dolore numquam.",
                            Time = new DateTime(2025, 3, 22, 18, 53, 56, 762, DateTimeKind.Unspecified).AddTicks(9754)
                        },
                        new
                        {
                            Id = 20,
                            ClientId = "9e942e34-9563-447a-a12b-e6cb31f25f3a",
                            Location = 0,
                            Note = "Sunt consequatur vel.\nDoloribus praesentium nam et laudantium iusto accusamus reiciendis eligendi.\nExplicabo soluta aut.",
                            Time = new DateTime(2025, 5, 4, 5, 23, 47, 577, DateTimeKind.Unspecified).AddTicks(7392)
                        },
                        new
                        {
                            Id = 21,
                            ClientId = "3a02dbc3-09cf-4511-9d8f-c40cc78c6285",
                            Location = 0,
                            Note = "Porro quo nisi maiores qui.\nEt debitis quisquam quo maxime.",
                            Time = new DateTime(2025, 6, 26, 22, 14, 31, 666, DateTimeKind.Unspecified).AddTicks(8076)
                        },
                        new
                        {
                            Id = 22,
                            ClientId = "79ab798a-f0da-45de-958c-4f88a3c1d3aa",
                            Location = 0,
                            Note = "Assumenda sed adipisci cumque tempore omnis nemo accusantium cupiditate harum.",
                            Time = new DateTime(2025, 6, 7, 22, 37, 39, 42, DateTimeKind.Unspecified).AddTicks(3434)
                        },
                        new
                        {
                            Id = 23,
                            ClientId = "9e942e34-9563-447a-a12b-e6cb31f25f3a",
                            Location = 0,
                            Note = "consequuntur",
                            Time = new DateTime(2025, 2, 25, 12, 19, 53, 7, DateTimeKind.Unspecified).AddTicks(5413)
                        },
                        new
                        {
                            Id = 24,
                            ClientId = "c21ae03e-c588-4605-94f0-0f8019c56299",
                            Location = 0,
                            Note = "Quidem ea qui ullam voluptas amet libero autem.\nQuisquam dolorem commodi aut accusamus quis nostrum sunt.\nPlaceat rerum repellendus excepturi repudiandae dolorum.\nVel ab at est eos rerum qui voluptatum.\nNihil omnis dolorem rerum sed modi.",
                            Time = new DateTime(2025, 6, 19, 12, 11, 28, 775, DateTimeKind.Unspecified).AddTicks(5007)
                        },
                        new
                        {
                            Id = 25,
                            ClientId = "c21ae03e-c588-4605-94f0-0f8019c56299",
                            Location = 0,
                            Note = "quidem",
                            Time = new DateTime(2025, 3, 18, 18, 22, 48, 80, DateTimeKind.Unspecified).AddTicks(7075)
                        },
                        new
                        {
                            Id = 26,
                            ClientId = "c21ae03e-c588-4605-94f0-0f8019c56299",
                            Location = 0,
                            Note = "In occaecati neque.",
                            Time = new DateTime(2025, 3, 16, 9, 8, 32, 179, DateTimeKind.Unspecified).AddTicks(8275)
                        },
                        new
                        {
                            Id = 27,
                            ClientId = "c21ae03e-c588-4605-94f0-0f8019c56299",
                            Location = 0,
                            Note = "consequatur",
                            Time = new DateTime(2025, 1, 29, 20, 36, 20, 285, DateTimeKind.Unspecified).AddTicks(7447)
                        },
                        new
                        {
                            Id = 28,
                            ClientId = "3a02dbc3-09cf-4511-9d8f-c40cc78c6285",
                            Location = 0,
                            Note = "et",
                            Time = new DateTime(2025, 4, 15, 17, 23, 1, 691, DateTimeKind.Unspecified).AddTicks(1381)
                        },
                        new
                        {
                            Id = 29,
                            ClientId = "21d2afc1-49fb-4e30-8ab1-8427709c9f2b",
                            Location = 0,
                            Note = "Officiis ea enim rem delectus dolores laboriosam debitis. Est asperiores dicta voluptatibus adipisci sapiente officiis illo quasi quia. Velit doloremque dolore eos dolorem aut laudantium dolore. Expedita quidem voluptatem eos optio molestiae quis voluptatem id.",
                            Time = new DateTime(2025, 1, 11, 19, 50, 40, 243, DateTimeKind.Unspecified).AddTicks(1052)
                        },
                        new
                        {
                            Id = 30,
                            ClientId = "3a02dbc3-09cf-4511-9d8f-c40cc78c6285",
                            Location = 0,
                            Note = "cupiditate",
                            Time = new DateTime(2025, 2, 23, 1, 26, 2, 74, DateTimeKind.Unspecified).AddTicks(3620)
                        });
                });

            modelBuilder.Entity("ClientPortal.Server.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "PersonalSite");

                    b.HasData(
                        new
                        {
                            Id = "cdd16811-d61a-44f1-8267-f1d4e8d82686",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3f844363-2243-4ee6-9d4f-9eda3f4ee7fb",
                            Email = "Melinda_Hermiston3@email.com",
                            EmailConfirmed = false,
                            FirstName = "Melinda",
                            LastName = "Hermiston",
                            LockoutEnabled = false,
                            NormalizedEmail = "melinda_hermiston3@email.com",
                            NormalizedUserName = "melinda_hermiston3@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEMdn/HzL1khHAL449424cX4Pnd4iamvA5lNDcfsYyTZG3nnEGcCe5K8gez7t4zN93A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8f520d69-ac61-4413-a4b7-70ce26667560",
                            TwoFactorEnabled = false,
                            UserName = "melinda_hermiston3@email.com"
                        },
                        new
                        {
                            Id = "79ab798a-f0da-45de-958c-4f88a3c1d3aa",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "07e11f47-42ac-4b52-b43d-8a0e2d34efdd",
                            Email = "Jeanne58@email.com",
                            EmailConfirmed = false,
                            FirstName = "Jeanne",
                            LastName = "Howell",
                            LockoutEnabled = false,
                            NormalizedEmail = "jeanne58@email.com",
                            NormalizedUserName = "jeanne58@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEPEOOZ7nT4WpDA5XLq7HfWyhliSnjTm+DMmvETQRsrkCqwg1eHdKCXECcWtjhfXgHQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d2b20940-d362-4b88-a230-71b9e2453fc9",
                            TwoFactorEnabled = false,
                            UserName = "jeanne58@email.com"
                        },
                        new
                        {
                            Id = "3a02dbc3-09cf-4511-9d8f-c40cc78c6285",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bea17a0c-b9af-4773-87f6-55ca5cdc24a0",
                            Email = "Darryl_Monahan15@email.com",
                            EmailConfirmed = false,
                            FirstName = "Darryl",
                            LastName = "Monahan",
                            LockoutEnabled = false,
                            NormalizedEmail = "darryl_monahan15@email.com",
                            NormalizedUserName = "darryl_monahan15@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEBGv8jxUE2y912/+rOVv0hD4Rvg9QBQjyW8RT8F2ZZ4jnWWchc/cTAJxHKeVJ+fhHA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "399f07c1-0945-427c-ab31-9594d3434f37",
                            TwoFactorEnabled = false,
                            UserName = "darryl_monahan15@email.com"
                        },
                        new
                        {
                            Id = "9e942e34-9563-447a-a12b-e6cb31f25f3a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a1850053-779f-46fc-93d2-39598ac7f460",
                            Email = "Sonja.Connelly58@email.com",
                            EmailConfirmed = false,
                            FirstName = "Sonja",
                            LastName = "Connelly",
                            LockoutEnabled = false,
                            NormalizedEmail = "sonja.connelly58@email.com",
                            NormalizedUserName = "sonja.connelly58@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEB6VxfiqdKOQaZyYUYdbpEZGhbnkuMC6P4i+qHPVP6WL0/BzNq2BTD5iUA5ZYIdHSw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d9eba852-3e93-41c0-ab8c-5452b5e74c2f",
                            TwoFactorEnabled = false,
                            UserName = "sonja.connelly58@email.com"
                        },
                        new
                        {
                            Id = "e5fba865-f5c4-47b5-aed2-5a46a186cb83",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "325484db-e01f-48f7-97cc-054711870902",
                            Email = "Vernon_Christiansen@email.com",
                            EmailConfirmed = false,
                            FirstName = "Vernon",
                            LastName = "Christiansen",
                            LockoutEnabled = false,
                            NormalizedEmail = "vernon_christiansen@email.com",
                            NormalizedUserName = "vernon_christiansen@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAENQJm4e4sfranMeqBLN4W/5M/SWW8ei/gtPoiGFJeq5R+edqCWK6xg3Kx1xRGywM9Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e7f2581d-342a-4ce2-803a-a60dd450b8d8",
                            TwoFactorEnabled = false,
                            UserName = "vernon_christiansen@email.com"
                        },
                        new
                        {
                            Id = "df986608-2a74-4168-84a7-043934b89456",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2dd4bba3-6873-4fb4-bd1b-b089cacc8994",
                            Email = "Erica_Hyatt83@email.com",
                            EmailConfirmed = false,
                            FirstName = "Erica",
                            LastName = "Hyatt",
                            LockoutEnabled = false,
                            NormalizedEmail = "erica_hyatt83@email.com",
                            NormalizedUserName = "erica_hyatt83@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEPA7vnkwuEAzRjoQRqKo0gokDdmmvjzVRER76STjbVApoTAhXyw2V15rVV21zvqY6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "80c37e26-d7a1-4c6d-bcba-688342a15d33",
                            TwoFactorEnabled = false,
                            UserName = "erica_hyatt83@email.com"
                        },
                        new
                        {
                            Id = "f2b75dde-ff5c-4c8f-8a44-5a7af46fc6d1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb96de82-966e-4fdf-9335-bb040872c8c2",
                            Email = "Elena_Feest@email.com",
                            EmailConfirmed = false,
                            FirstName = "Elena",
                            LastName = "Feest",
                            LockoutEnabled = false,
                            NormalizedEmail = "elena_feest@email.com",
                            NormalizedUserName = "elena_feest@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEEU2cMe0BvlM8KcJsm/Jy99fDh9eVV7R6w6hrVcohw5bvDuPt2fzIpCKd/4/Mg+ENw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4f2a891a-0bed-49b3-aa33-2c3b972966d3",
                            TwoFactorEnabled = false,
                            UserName = "elena_feest@email.com"
                        },
                        new
                        {
                            Id = "30095dca-b53e-4f33-90b8-a213ebf2883f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "00070f97-a591-4731-be03-91da72b8bcbf",
                            Email = "Gordon.Gislason@email.com",
                            EmailConfirmed = false,
                            FirstName = "Gordon",
                            LastName = "Gislason",
                            LockoutEnabled = false,
                            NormalizedEmail = "gordon.gislason@email.com",
                            NormalizedUserName = "gordon.gislason@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEARgrMZFxsEsrwPGe+R8NgcK+naHwVxJ4sNJeJNElzqxEPGmJBB12LoAlT7LaXPM7g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ee98ffe4-a90a-4bf0-9725-db7556232cf5",
                            TwoFactorEnabled = false,
                            UserName = "gordon.gislason@email.com"
                        },
                        new
                        {
                            Id = "c21ae03e-c588-4605-94f0-0f8019c56299",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "edfe3238-6030-4526-8289-b11ccf7d09e4",
                            Email = "Cornelius46@email.com",
                            EmailConfirmed = false,
                            FirstName = "Cornelius",
                            LastName = "Beatty",
                            LockoutEnabled = false,
                            NormalizedEmail = "cornelius46@email.com",
                            NormalizedUserName = "cornelius46@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEKeq4HBuvm9g+v6cnbxtLn/dIbGa2uRHMk2Zo6cawIHdsQyzYGAXiGWrQL/uB9hUfQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6c6b6916-8cf6-4996-9b32-68da85a4bb54",
                            TwoFactorEnabled = false,
                            UserName = "cornelius46@email.com"
                        },
                        new
                        {
                            Id = "21d2afc1-49fb-4e30-8ab1-8427709c9f2b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "97eb897b-6899-491d-ac6c-aa6748e01b07",
                            Email = "Irving_Gibson82@email.com",
                            EmailConfirmed = false,
                            FirstName = "Irving",
                            LastName = "Gibson",
                            LockoutEnabled = false,
                            NormalizedEmail = "irving_gibson82@email.com",
                            NormalizedUserName = "irving_gibson82@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEA0W9B8ooRSLmJb3ZOgGYk2VTH9vrHP8AGEARVdV7ZRFYqghKH/SIhyyHdCcBX6nEw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dcc55f8b-b10e-4837-be78-00b1bf90a453",
                            TwoFactorEnabled = false,
                            UserName = "irving_gibson82@email.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "PersonalSite");

                    b.HasData(
                        new
                        {
                            Id = "89e922f9-758b-493d-9ec0-8b9af6b18b61",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = "4a2a713f-bdc9-45c5-969f-6411da61f098",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "PersonalSite");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "PersonalSite");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "PersonalSite");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "PersonalSite");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "PersonalSite");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClientPortal.Server.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClientPortal.Server.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClientPortal.Server.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClientPortal.Server.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
