// <auto-generated />
using System;
using AlchemyCoaching.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlchemyCoaching.Server.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20250604190046_fresh_database")]
    partial class fresh_database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("AlchemyCoaching")
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientPortal.Server.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Appointment", "AlchemyCoaching");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = "e0b1b8e1-31c9-495d-bc9b-8f3a47c20988",
                            Location = 0,
                            Note = "Suscipit ipsum ea aliquid aut ut omnis et quo. Natus nisi est vero consequuntur qui. Quibusdam nihil sit. Itaque repellat excepturi accusamus sed. Enim praesentium voluptas optio tenetur et et similique magni.",
                            Time = new DateTime(2025, 2, 23, 19, 59, 53, 108, DateTimeKind.Unspecified).AddTicks(3833)
                        },
                        new
                        {
                            Id = 2,
                            ClientId = "9844b374-0a9a-486f-8d6d-86fc85c6ceb0",
                            Location = 0,
                            Note = "Eius facilis id quis architecto.\nNon voluptas iusto sint sit et autem consequatur.\nEst et voluptatem magni illo delectus est.\nVelit tempora libero omnis et sit autem laborum.\nVoluptatem similique consectetur reprehenderit modi est quia et corrupti.",
                            Time = new DateTime(2025, 3, 11, 23, 13, 56, 761, DateTimeKind.Unspecified).AddTicks(3110)
                        },
                        new
                        {
                            Id = 3,
                            ClientId = "e0b1b8e1-31c9-495d-bc9b-8f3a47c20988",
                            Location = 0,
                            Note = "Aliquam ut et dicta velit quibusdam ut numquam voluptatum.\nDolores eius at debitis sint.",
                            Time = new DateTime(2025, 1, 25, 23, 37, 28, 112, DateTimeKind.Unspecified).AddTicks(7457)
                        },
                        new
                        {
                            Id = 4,
                            ClientId = "7bb53c7e-feae-47c3-9bf8-d47e4b66055b",
                            Location = 0,
                            Note = "Consectetur aliquam sunt et corrupti molestiae aut accusamus aperiam. Excepturi suscipit aliquam autem sunt vitae quia. Reiciendis tempora autem qui dolore.",
                            Time = new DateTime(2025, 3, 29, 7, 2, 13, 33, DateTimeKind.Unspecified).AddTicks(7589)
                        },
                        new
                        {
                            Id = 5,
                            ClientId = "9844b374-0a9a-486f-8d6d-86fc85c6ceb0",
                            Location = 0,
                            Note = "Consectetur libero pariatur aut sed. Explicabo porro ut qui quis qui recusandae. Tenetur hic in qui quis. Asperiores sunt ducimus quo. Ducimus quae est tempora sed.",
                            Time = new DateTime(2025, 6, 13, 14, 10, 46, 477, DateTimeKind.Unspecified).AddTicks(4921)
                        },
                        new
                        {
                            Id = 6,
                            ClientId = "a2d15849-5376-4e4b-af5d-accb1ffa3935",
                            Location = 0,
                            Note = "Occaecati minus voluptatum non velit qui earum.",
                            Time = new DateTime(2025, 4, 24, 0, 2, 9, 39, DateTimeKind.Unspecified).AddTicks(4056)
                        },
                        new
                        {
                            Id = 7,
                            ClientId = "d61ac6e5-72e0-4e5a-9946-10c694abeef6",
                            Location = 0,
                            Note = "eos",
                            Time = new DateTime(2025, 1, 6, 23, 47, 20, 969, DateTimeKind.Unspecified).AddTicks(6472)
                        },
                        new
                        {
                            Id = 8,
                            ClientId = "8356b7ff-89f7-4835-b16a-7eca2102bd5b",
                            Location = 0,
                            Note = "Veniam ut facilis consequatur soluta.",
                            Time = new DateTime(2025, 2, 22, 14, 5, 43, 187, DateTimeKind.Unspecified).AddTicks(9180)
                        },
                        new
                        {
                            Id = 9,
                            ClientId = "8356b7ff-89f7-4835-b16a-7eca2102bd5b",
                            Location = 0,
                            Note = "Expedita repellendus odit.\nQuas unde est quo cumque.\nUt odit dolores rem omnis illo.",
                            Time = new DateTime(2025, 6, 3, 19, 18, 18, 215, DateTimeKind.Unspecified).AddTicks(5637)
                        },
                        new
                        {
                            Id = 10,
                            ClientId = "f8294be2-341c-4a94-97c6-6e9f2a189070",
                            Location = 0,
                            Note = "Ullam earum minus. Mollitia doloremque ea maiores. Expedita qui aliquid illum eum fugit.",
                            Time = new DateTime(2025, 3, 3, 20, 11, 38, 254, DateTimeKind.Unspecified).AddTicks(6213)
                        },
                        new
                        {
                            Id = 11,
                            ClientId = "f8294be2-341c-4a94-97c6-6e9f2a189070",
                            Location = 0,
                            Note = "Quia consequatur rerum dolores eligendi voluptas temporibus est officiis.",
                            Time = new DateTime(2025, 1, 12, 7, 12, 51, 681, DateTimeKind.Unspecified).AddTicks(421)
                        },
                        new
                        {
                            Id = 12,
                            ClientId = "8356b7ff-89f7-4835-b16a-7eca2102bd5b",
                            Location = 0,
                            Note = "Ducimus perspiciatis dolores.\nQuo ut odio cumque amet vel.\nVoluptas repudiandae eveniet quis odio dignissimos facilis dolorem fugiat.\nNostrum earum vitae.\nBlanditiis cum expedita maiores ducimus eos nam libero.",
                            Time = new DateTime(2025, 4, 3, 1, 6, 59, 344, DateTimeKind.Unspecified).AddTicks(4658)
                        },
                        new
                        {
                            Id = 13,
                            ClientId = "a2d15849-5376-4e4b-af5d-accb1ffa3935",
                            Location = 0,
                            Note = "At animi id officiis nesciunt rerum non soluta.",
                            Time = new DateTime(2025, 6, 4, 2, 2, 30, 798, DateTimeKind.Unspecified).AddTicks(918)
                        },
                        new
                        {
                            Id = 14,
                            ClientId = "2618f4d1-f4a8-4584-901c-57b233900da2",
                            Location = 0,
                            Note = "Sed et labore maxime.",
                            Time = new DateTime(2025, 1, 27, 2, 42, 39, 692, DateTimeKind.Unspecified).AddTicks(8840)
                        },
                        new
                        {
                            Id = 15,
                            ClientId = "9844b374-0a9a-486f-8d6d-86fc85c6ceb0",
                            Location = 0,
                            Note = "Cupiditate explicabo nesciunt sint quam nostrum laboriosam autem suscipit repellendus. Rerum quia rerum. Libero animi aliquid quibusdam. Animi dolorem error eius adipisci molestiae dolorem deleniti. Molestias eaque corrupti et recusandae earum voluptas deserunt minima.",
                            Time = new DateTime(2025, 4, 6, 15, 58, 38, 318, DateTimeKind.Unspecified).AddTicks(4020)
                        },
                        new
                        {
                            Id = 16,
                            ClientId = "8356b7ff-89f7-4835-b16a-7eca2102bd5b",
                            Location = 0,
                            Note = "omnis",
                            Time = new DateTime(2025, 3, 20, 18, 41, 11, 605, DateTimeKind.Unspecified).AddTicks(2365)
                        },
                        new
                        {
                            Id = 17,
                            ClientId = "2618f4d1-f4a8-4584-901c-57b233900da2",
                            Location = 0,
                            Note = "Maiores vero qui.\nQui consequatur eos qui qui cupiditate quia alias.\nVoluptas est est molestiae alias ut asperiores.\nRepellat tenetur explicabo provident aliquid ea quia.",
                            Time = new DateTime(2025, 3, 28, 22, 47, 17, 551, DateTimeKind.Unspecified).AddTicks(1237)
                        },
                        new
                        {
                            Id = 18,
                            ClientId = "8356b7ff-89f7-4835-b16a-7eca2102bd5b",
                            Location = 0,
                            Note = "Magnam placeat est repudiandae quaerat id ut minima omnis occaecati. Et non consequatur qui ipsa perferendis. Enim commodi repudiandae quisquam ab. Est sint autem est dicta.",
                            Time = new DateTime(2025, 4, 21, 18, 44, 45, 87, DateTimeKind.Unspecified).AddTicks(6746)
                        },
                        new
                        {
                            Id = 19,
                            ClientId = "f8294be2-341c-4a94-97c6-6e9f2a189070",
                            Location = 0,
                            Note = "Ut sint consequatur unde ut.\nQuasi facere eligendi et id saepe.\nQuae repudiandae animi et eos numquam dolorem voluptas.\nAliquam qui harum qui aliquid placeat eligendi expedita.",
                            Time = new DateTime(2025, 5, 21, 23, 44, 47, 614, DateTimeKind.Unspecified).AddTicks(6450)
                        },
                        new
                        {
                            Id = 20,
                            ClientId = "e0b1b8e1-31c9-495d-bc9b-8f3a47c20988",
                            Location = 0,
                            Note = "Commodi quaerat enim repellat et quaerat.\nSequi hic neque.\nIpsa ad rem porro explicabo pariatur adipisci consequatur.",
                            Time = new DateTime(2025, 1, 2, 13, 44, 19, 315, DateTimeKind.Unspecified).AddTicks(3556)
                        },
                        new
                        {
                            Id = 21,
                            ClientId = "9844b374-0a9a-486f-8d6d-86fc85c6ceb0",
                            Location = 0,
                            Note = "Non sed ad odio deserunt voluptatum ut.\nEum aut veniam nemo non ipsam delectus fugiat cupiditate unde.",
                            Time = new DateTime(2025, 3, 4, 20, 14, 6, 883, DateTimeKind.Unspecified).AddTicks(4956)
                        },
                        new
                        {
                            Id = 22,
                            ClientId = "9844b374-0a9a-486f-8d6d-86fc85c6ceb0",
                            Location = 0,
                            Note = "aut",
                            Time = new DateTime(2025, 2, 25, 8, 28, 49, 583, DateTimeKind.Unspecified).AddTicks(8992)
                        },
                        new
                        {
                            Id = 23,
                            ClientId = "2618f4d1-f4a8-4584-901c-57b233900da2",
                            Location = 0,
                            Note = "Labore repellendus eius sit et cupiditate.",
                            Time = new DateTime(2025, 2, 16, 2, 11, 53, 451, DateTimeKind.Unspecified).AddTicks(6484)
                        },
                        new
                        {
                            Id = 24,
                            ClientId = "7bb53c7e-feae-47c3-9bf8-d47e4b66055b",
                            Location = 0,
                            Note = "Error sunt id iure. Autem aut est. A nihil eos voluptatem quibusdam voluptatem ea fugit quis dolorem. Ratione quibusdam rerum.",
                            Time = new DateTime(2025, 3, 30, 11, 36, 59, 627, DateTimeKind.Unspecified).AddTicks(8774)
                        },
                        new
                        {
                            Id = 25,
                            ClientId = "d61ac6e5-72e0-4e5a-9946-10c694abeef6",
                            Location = 0,
                            Note = "Nihil cum sit rerum.",
                            Time = new DateTime(2025, 3, 8, 23, 42, 16, 784, DateTimeKind.Unspecified).AddTicks(7634)
                        },
                        new
                        {
                            Id = 26,
                            ClientId = "1e0ff4af-05e6-4dc4-ad25-edec7652ff45",
                            Location = 0,
                            Note = "Unde qui nemo autem provident atque. Aut voluptate ab omnis quaerat exercitationem dicta. Ad commodi maiores eius est in nostrum autem maiores et. Impedit repellendus autem.",
                            Time = new DateTime(2025, 4, 19, 17, 8, 1, 513, DateTimeKind.Unspecified).AddTicks(271)
                        },
                        new
                        {
                            Id = 27,
                            ClientId = "2618f4d1-f4a8-4584-901c-57b233900da2",
                            Location = 0,
                            Note = "explicabo",
                            Time = new DateTime(2025, 4, 27, 18, 54, 57, 919, DateTimeKind.Unspecified).AddTicks(2434)
                        },
                        new
                        {
                            Id = 28,
                            ClientId = "2618f4d1-f4a8-4584-901c-57b233900da2",
                            Location = 0,
                            Note = "Praesentium molestias aut praesentium consequatur quibusdam natus ullam odio.\nAsperiores quia labore quae eius.",
                            Time = new DateTime(2025, 6, 2, 19, 29, 35, 637, DateTimeKind.Unspecified).AddTicks(2515)
                        },
                        new
                        {
                            Id = 29,
                            ClientId = "8356b7ff-89f7-4835-b16a-7eca2102bd5b",
                            Location = 0,
                            Note = "Dicta incidunt aliquid ratione sit saepe ut. Assumenda nihil minus soluta natus amet sit. Aut laboriosam occaecati qui. Nobis eius ut dicta debitis laborum non illo.",
                            Time = new DateTime(2025, 5, 14, 5, 24, 13, 621, DateTimeKind.Unspecified).AddTicks(9668)
                        },
                        new
                        {
                            Id = 30,
                            ClientId = "7bb53c7e-feae-47c3-9bf8-d47e4b66055b",
                            Location = 0,
                            Note = "Fuga vel perferendis. Voluptatem quo quos perspiciatis. Natus eos recusandae. Neque et qui voluptatem earum quisquam suscipit voluptates. Doloribus et est ipsum aut quia ut. Quisquam velit architecto voluptas nam modi quod commodi nulla.",
                            Time = new DateTime(2025, 2, 5, 7, 55, 26, 861, DateTimeKind.Unspecified).AddTicks(1445)
                        });
                });

            modelBuilder.Entity("ClientPortal.Server.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "AlchemyCoaching");

                    b.HasData(
                        new
                        {
                            Id = "41ef70d3-b947-4099-b772-b77df022cc23",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "31bf2d74-5667-480b-89d6-ddda4d390455",
                            Email = "Jacquelyn.Cormier18@email.com",
                            EmailConfirmed = false,
                            FirstName = "Jacquelyn",
                            LastName = "Cormier",
                            LockoutEnabled = false,
                            NormalizedEmail = "jacquelyn.cormier18@email.com",
                            NormalizedUserName = "jacquelyn.cormier18@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEDN4LQVIBLgPAu22eoblaR8OvgIy5eJOw+ucT6MowgTrgIc6YzCAPfIvFAFWQq0qdw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "050706dc-8efe-4b44-b7b6-8401efb0d3ad",
                            TwoFactorEnabled = false,
                            UserName = "jacquelyn.cormier18@email.com"
                        },
                        new
                        {
                            Id = "7bb53c7e-feae-47c3-9bf8-d47e4b66055b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "759a5282-1d52-44ac-bad1-a30bdf3839c7",
                            Email = "Herbert_Luettgen9@email.com",
                            EmailConfirmed = false,
                            FirstName = "Herbert",
                            LastName = "Luettgen",
                            LockoutEnabled = false,
                            NormalizedEmail = "herbert_luettgen9@email.com",
                            NormalizedUserName = "herbert_luettgen9@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAENUqiP38AGTJVrzLh+GXAgQ5mXQnJfK7enPavBlNFpkq5fjd93sUtnU2JaePAviiAQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "33852f04-0f51-4bf8-9b94-42cabbce8c60",
                            TwoFactorEnabled = false,
                            UserName = "herbert_luettgen9@email.com"
                        },
                        new
                        {
                            Id = "a2d15849-5376-4e4b-af5d-accb1ffa3935",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7e7c26c2-c51c-42d8-ac40-b8f616b6080e",
                            Email = "Hector.Jenkins8@email.com",
                            EmailConfirmed = false,
                            FirstName = "Hector",
                            LastName = "Jenkins",
                            LockoutEnabled = false,
                            NormalizedEmail = "hector.jenkins8@email.com",
                            NormalizedUserName = "hector.jenkins8@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEHgL/njMypSb2Jsa6ihRNosrDw2wP4IeCeHVNyE0UyoOvwqO8j2cVMgMHy2bZ5AOVA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d472ab5d-f198-45d8-98ea-c6ebf168c797",
                            TwoFactorEnabled = false,
                            UserName = "hector.jenkins8@email.com"
                        },
                        new
                        {
                            Id = "f8294be2-341c-4a94-97c6-6e9f2a189070",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "804e72ec-bfd2-4f7c-93b6-c0e75a4208cf",
                            Email = "Kelli.Schumm67@email.com",
                            EmailConfirmed = false,
                            FirstName = "Kelli",
                            LastName = "Schumm",
                            LockoutEnabled = false,
                            NormalizedEmail = "kelli.schumm67@email.com",
                            NormalizedUserName = "kelli.schumm67@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEDdYtKRXPjhuIKKPrYGLDU7CU0X8R0nCRfwbTkrqG1bYEAvGf0figSNVpSLbgiS2CQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bbf7425d-c9b9-45c5-a242-90af889b6645",
                            TwoFactorEnabled = false,
                            UserName = "kelli.schumm67@email.com"
                        },
                        new
                        {
                            Id = "1e0ff4af-05e6-4dc4-ad25-edec7652ff45",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "29c2fa94-2db2-45fb-805e-18192cc21d22",
                            Email = "Lula.Orn57@email.com",
                            EmailConfirmed = false,
                            FirstName = "Lula",
                            LastName = "Orn",
                            LockoutEnabled = false,
                            NormalizedEmail = "lula.orn57@email.com",
                            NormalizedUserName = "lula.orn57@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEN5yfCNehYd6NrrE2nyCJZSyal7qxJS4897qUvs8D8HWi/2mAZ/DZrfMyYuLclU6lw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "670675a8-4060-4981-bc19-3918258e3b7f",
                            TwoFactorEnabled = false,
                            UserName = "lula.orn57@email.com"
                        },
                        new
                        {
                            Id = "d61ac6e5-72e0-4e5a-9946-10c694abeef6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1a07b1bc-9bb5-4eaf-9b90-06e61ed740f7",
                            Email = "Paulette.Heaney@email.com",
                            EmailConfirmed = false,
                            FirstName = "Paulette",
                            LastName = "Heaney",
                            LockoutEnabled = false,
                            NormalizedEmail = "paulette.heaney@email.com",
                            NormalizedUserName = "paulette.heaney@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEPENMUUfZatwDPzB+ecInS9Dcv2cqHhiraOoh9YhDe6oK5L41dWj6daJGtEC5Wfs1g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "735f10d4-5d2d-4ed5-a2ed-5366bc0dc217",
                            TwoFactorEnabled = false,
                            UserName = "paulette.heaney@email.com"
                        },
                        new
                        {
                            Id = "2618f4d1-f4a8-4584-901c-57b233900da2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "acb2feb5-9758-4451-88ee-3c3929d4017c",
                            Email = "Katie_Terry@email.com",
                            EmailConfirmed = false,
                            FirstName = "Katie",
                            LastName = "Terry",
                            LockoutEnabled = false,
                            NormalizedEmail = "katie_terry@email.com",
                            NormalizedUserName = "katie_terry@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEIZJG2ErxEyoVFxGwxXQ3/BwUbA3Owak0E6Q8xL75Ty147jy/gskKNmFnsZD4tMhVA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6c9ab80f-db3f-4d21-a952-c4cdb0e47907",
                            TwoFactorEnabled = false,
                            UserName = "katie_terry@email.com"
                        },
                        new
                        {
                            Id = "9844b374-0a9a-486f-8d6d-86fc85c6ceb0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b9dcfc1a-d447-4048-ad0b-d130d013b9a5",
                            Email = "Agnes_Wolf@email.com",
                            EmailConfirmed = false,
                            FirstName = "Agnes",
                            LastName = "Wolf",
                            LockoutEnabled = false,
                            NormalizedEmail = "agnes_wolf@email.com",
                            NormalizedUserName = "agnes_wolf@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEA1xhosSSEA9dPj2zziNqmoFHWCzwK17mOysS4vOEW3bP+E4E/1MPJ/oLjZbUr5KGg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "64e2c042-f0c0-42eb-9f57-2a4a7bdc0343",
                            TwoFactorEnabled = false,
                            UserName = "agnes_wolf@email.com"
                        },
                        new
                        {
                            Id = "e0b1b8e1-31c9-495d-bc9b-8f3a47c20988",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c4f60b9d-1295-4cd4-90e4-c64591946504",
                            Email = "Gregg69@email.com",
                            EmailConfirmed = false,
                            FirstName = "Gregg",
                            LastName = "Larson",
                            LockoutEnabled = false,
                            NormalizedEmail = "gregg69@email.com",
                            NormalizedUserName = "gregg69@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAELWZywuRjh5KRlyJq9ShgzkBrsg/U0M0bM4Obr/NhJtZhIZEZCaDGWD0LGs34xrLXg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fe0f98df-895e-4a2e-8b97-1abfb1ea2ca3",
                            TwoFactorEnabled = false,
                            UserName = "gregg69@email.com"
                        },
                        new
                        {
                            Id = "8356b7ff-89f7-4835-b16a-7eca2102bd5b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "755f8ed0-0de5-4edf-a184-64ded9cfdfe8",
                            Email = "Eloise35@email.com",
                            EmailConfirmed = false,
                            FirstName = "Eloise",
                            LastName = "Olson",
                            LockoutEnabled = false,
                            NormalizedEmail = "eloise35@email.com",
                            NormalizedUserName = "eloise35@email.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEOe+J423dW7wCeSpVCy7vnFnrPLeqLsYYEIyqYv6/cu7HEJxfgVmT1nkgWO9NyDNsQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "56df5e7b-2ff0-441f-8039-0b4298813ee9",
                            TwoFactorEnabled = false,
                            UserName = "eloise35@email.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "AlchemyCoaching");

                    b.HasData(
                        new
                        {
                            Id = "761481ad-b971-49b9-9389-1f0599751dd6",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = "53c128ff-e28d-4f22-908c-12abed534cc5",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "AlchemyCoaching");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "AlchemyCoaching");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "AlchemyCoaching");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "AlchemyCoaching");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "AlchemyCoaching");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClientPortal.Server.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClientPortal.Server.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClientPortal.Server.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClientPortal.Server.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
