// <auto-generated />
using System;
using AlchemyCoaching.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlchemyCoaching.Server.Migrations
{
    [DbContext(typeof(AlchemyDbContext))]
    partial class AlchemyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("AlchemyCoaching")
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlchemyCoaching.Server.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Coach")
                        .HasColumnType("int");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Appointment", "AlchemyCoaching");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = "c44a61c6-ccd9-47c8-be98-d6e9f935c8b7",
                            Coach = 0,
                            Location = 0,
                            Note = "Totam velit maiores possimus.\nMaiores est iste autem numquam voluptatem.\nQuaerat animi eius nihil exercitationem nam qui.\nRatione et possimus neque temporibus hic.",
                            Time = new DateTime(2025, 10, 9, 8, 2, 17, 286, DateTimeKind.Unspecified).AddTicks(8041)
                        },
                        new
                        {
                            Id = 2,
                            ClientId = "e0e696be-4ca5-42bf-89d9-10ed98fbbc7a",
                            Coach = 0,
                            Location = 0,
                            Note = "Nemo iure distinctio saepe atque nesciunt quisquam molestiae iusto perspiciatis. Inventore nisi veritatis quos ab cum vel suscipit minima. Facere dolorem assumenda aut sunt eum temporibus veniam. Veritatis tempore quibusdam qui.",
                            Time = new DateTime(2025, 9, 23, 18, 50, 57, 759, DateTimeKind.Unspecified).AddTicks(6054)
                        },
                        new
                        {
                            Id = 3,
                            ClientId = "fe217307-3574-401b-b0a2-535921d6c7f0",
                            Coach = 0,
                            Location = 0,
                            Note = "Qui quod unde aliquid eaque odit quidem aperiam.\nEt aspernatur sed rerum perspiciatis non non vel aut.\nNobis culpa animi et sed dolores neque et.\nEt vel corporis dolor reprehenderit repellendus et labore doloremque ut.\nEt molestias provident dolor.",
                            Time = new DateTime(2025, 3, 14, 20, 37, 22, 150, DateTimeKind.Unspecified).AddTicks(8785)
                        },
                        new
                        {
                            Id = 4,
                            ClientId = "1001c0f2-a1cf-4ce0-9c92-659ee13859b5",
                            Coach = 0,
                            Location = 0,
                            Note = "Tenetur aliquid deleniti sit aut quas voluptas repudiandae veniam quaerat.",
                            Time = new DateTime(2025, 12, 29, 3, 42, 38, 130, DateTimeKind.Unspecified).AddTicks(7945)
                        },
                        new
                        {
                            Id = 5,
                            ClientId = "b1aeda4b-5069-4bbb-8a97-00f494a2621e",
                            Coach = 0,
                            Location = 0,
                            Note = "Distinctio aut ut modi nihil asperiores ducimus distinctio.\nEum nobis accusantium mollitia dolore ut.",
                            Time = new DateTime(2025, 12, 26, 8, 22, 45, 922, DateTimeKind.Unspecified).AddTicks(8119)
                        },
                        new
                        {
                            Id = 6,
                            ClientId = "c5b75e07-e765-49ce-ae20-276264355634",
                            Coach = 0,
                            Location = 0,
                            Note = "cum",
                            Time = new DateTime(2025, 12, 10, 12, 11, 16, 391, DateTimeKind.Unspecified).AddTicks(9211)
                        },
                        new
                        {
                            Id = 7,
                            ClientId = "2b8d00ad-ec68-45a7-9b6e-c8f76e5dd390",
                            Coach = 0,
                            Location = 0,
                            Note = "aut",
                            Time = new DateTime(2025, 11, 9, 19, 29, 52, 391, DateTimeKind.Unspecified).AddTicks(9723)
                        },
                        new
                        {
                            Id = 8,
                            ClientId = "2b8d00ad-ec68-45a7-9b6e-c8f76e5dd390",
                            Coach = 0,
                            Location = 0,
                            Note = "iste",
                            Time = new DateTime(2025, 7, 19, 14, 15, 14, 937, DateTimeKind.Unspecified).AddTicks(1732)
                        },
                        new
                        {
                            Id = 9,
                            ClientId = "1001c0f2-a1cf-4ce0-9c92-659ee13859b5",
                            Coach = 0,
                            Location = 0,
                            Note = "tenetur",
                            Time = new DateTime(2025, 8, 30, 0, 26, 13, 931, DateTimeKind.Unspecified).AddTicks(6545)
                        },
                        new
                        {
                            Id = 10,
                            ClientId = "b1aeda4b-5069-4bbb-8a97-00f494a2621e",
                            Coach = 0,
                            Location = 0,
                            Note = "eius",
                            Time = new DateTime(2025, 7, 17, 0, 46, 36, 301, DateTimeKind.Unspecified).AddTicks(8530)
                        },
                        new
                        {
                            Id = 11,
                            ClientId = "b1aeda4b-5069-4bbb-8a97-00f494a2621e",
                            Coach = 0,
                            Location = 0,
                            Note = "Quas ut rem alias cupiditate at doloremque. Minima similique rerum ducimus reprehenderit ut voluptatem. Sed ut autem doloremque necessitatibus beatae sint rerum rem.",
                            Time = new DateTime(2025, 4, 22, 19, 46, 9, 27, DateTimeKind.Unspecified).AddTicks(4049)
                        },
                        new
                        {
                            Id = 12,
                            ClientId = "c44a61c6-ccd9-47c8-be98-d6e9f935c8b7",
                            Coach = 0,
                            Location = 0,
                            Note = "ut",
                            Time = new DateTime(2025, 6, 3, 23, 20, 47, 639, DateTimeKind.Unspecified).AddTicks(6976)
                        },
                        new
                        {
                            Id = 13,
                            ClientId = "1001c0f2-a1cf-4ce0-9c92-659ee13859b5",
                            Coach = 0,
                            Location = 0,
                            Note = "Consequatur odio quis aut tenetur id inventore.",
                            Time = new DateTime(2025, 1, 13, 16, 0, 6, 597, DateTimeKind.Unspecified).AddTicks(8834)
                        },
                        new
                        {
                            Id = 14,
                            ClientId = "727be5c6-1379-46ab-b486-5ed9a2054a83",
                            Coach = 0,
                            Location = 0,
                            Note = "non",
                            Time = new DateTime(2025, 3, 21, 0, 15, 47, 31, DateTimeKind.Unspecified).AddTicks(9597)
                        },
                        new
                        {
                            Id = 15,
                            ClientId = "ebe8c31b-02bf-4e19-83bc-8736c5697039",
                            Coach = 0,
                            Location = 0,
                            Note = "Quis iure recusandae voluptatem.",
                            Time = new DateTime(2025, 9, 22, 4, 23, 58, 588, DateTimeKind.Unspecified).AddTicks(8983)
                        },
                        new
                        {
                            Id = 16,
                            ClientId = "b1aeda4b-5069-4bbb-8a97-00f494a2621e",
                            Coach = 0,
                            Location = 0,
                            Note = "Ut harum sit ab odit fugiat aliquid suscipit quod molestiae.\nQui asperiores ab atque incidunt voluptatum optio ut nihil eveniet.\nAsperiores nulla dolorum amet et.\nTotam placeat ut amet dolores nemo consequuntur.",
                            Time = new DateTime(2025, 10, 29, 18, 55, 16, 8, DateTimeKind.Unspecified).AddTicks(3272)
                        },
                        new
                        {
                            Id = 17,
                            ClientId = "c5b75e07-e765-49ce-ae20-276264355634",
                            Coach = 0,
                            Location = 0,
                            Note = "Sit vitae illo in fugit aut aut vel cumque.\nVoluptas facilis perspiciatis ipsa soluta voluptas.",
                            Time = new DateTime(2025, 3, 7, 12, 40, 33, 91, DateTimeKind.Unspecified).AddTicks(640)
                        },
                        new
                        {
                            Id = 18,
                            ClientId = "b1aeda4b-5069-4bbb-8a97-00f494a2621e",
                            Coach = 0,
                            Location = 0,
                            Note = "eveniet",
                            Time = new DateTime(2025, 4, 11, 12, 58, 33, 405, DateTimeKind.Unspecified).AddTicks(8607)
                        },
                        new
                        {
                            Id = 19,
                            ClientId = "c5b75e07-e765-49ce-ae20-276264355634",
                            Coach = 0,
                            Location = 0,
                            Note = "Dolor enim officia officiis quam id quisquam aut.",
                            Time = new DateTime(2025, 5, 6, 22, 28, 36, 120, DateTimeKind.Unspecified).AddTicks(7643)
                        },
                        new
                        {
                            Id = 20,
                            ClientId = "727be5c6-1379-46ab-b486-5ed9a2054a83",
                            Coach = 0,
                            Location = 0,
                            Note = "Temporibus unde recusandae dignissimos corporis vero.\nEt optio ipsum.\nAccusantium doloribus ab ut quis dicta dolorum autem.\nNemo autem rerum cum reprehenderit et nihil dolorem.\nEa eius tempore quae reiciendis.\nEt dolor voluptate aut et qui laboriosam.",
                            Time = new DateTime(2025, 2, 28, 16, 43, 23, 286, DateTimeKind.Unspecified).AddTicks(3174)
                        },
                        new
                        {
                            Id = 21,
                            ClientId = "c5b75e07-e765-49ce-ae20-276264355634",
                            Coach = 0,
                            Location = 0,
                            Note = "ratione",
                            Time = new DateTime(2025, 12, 11, 11, 26, 24, 220, DateTimeKind.Unspecified).AddTicks(749)
                        },
                        new
                        {
                            Id = 22,
                            ClientId = "fe217307-3574-401b-b0a2-535921d6c7f0",
                            Coach = 0,
                            Location = 0,
                            Note = "molestiae",
                            Time = new DateTime(2025, 9, 26, 2, 51, 30, 883, DateTimeKind.Unspecified).AddTicks(9434)
                        },
                        new
                        {
                            Id = 23,
                            ClientId = "727be5c6-1379-46ab-b486-5ed9a2054a83",
                            Coach = 0,
                            Location = 0,
                            Note = "Provident sed rem est nobis qui nesciunt dolor hic odio.",
                            Time = new DateTime(2025, 7, 26, 7, 13, 37, 336, DateTimeKind.Unspecified).AddTicks(648)
                        },
                        new
                        {
                            Id = 24,
                            ClientId = "2b8d00ad-ec68-45a7-9b6e-c8f76e5dd390",
                            Coach = 0,
                            Location = 0,
                            Note = "Animi modi est.\nAut illum recusandae voluptas enim beatae excepturi totam occaecati.\nInventore voluptas dolorem qui perspiciatis officia.\nIure at error mollitia vel magnam temporibus.\nEt et molestias.",
                            Time = new DateTime(2025, 12, 8, 9, 52, 2, 685, DateTimeKind.Unspecified).AddTicks(8480)
                        },
                        new
                        {
                            Id = 25,
                            ClientId = "ebe8c31b-02bf-4e19-83bc-8736c5697039",
                            Coach = 0,
                            Location = 0,
                            Note = "iusto",
                            Time = new DateTime(2025, 2, 13, 13, 7, 0, 514, DateTimeKind.Unspecified).AddTicks(6871)
                        },
                        new
                        {
                            Id = 26,
                            ClientId = "c5b75e07-e765-49ce-ae20-276264355634",
                            Coach = 0,
                            Location = 0,
                            Note = "Sit tempore sed commodi vel repudiandae consequatur labore.",
                            Time = new DateTime(2025, 3, 15, 22, 36, 18, 640, DateTimeKind.Unspecified).AddTicks(3441)
                        },
                        new
                        {
                            Id = 27,
                            ClientId = "1001c0f2-a1cf-4ce0-9c92-659ee13859b5",
                            Coach = 0,
                            Location = 0,
                            Note = "Veniam suscipit saepe sit odio quia ducimus.\nIncidunt est mollitia ut veritatis.\nAut modi eaque ipsum perspiciatis nihil id totam eum ipsam.",
                            Time = new DateTime(2025, 5, 9, 7, 33, 16, 870, DateTimeKind.Unspecified).AddTicks(8203)
                        },
                        new
                        {
                            Id = 28,
                            ClientId = "c5b75e07-e765-49ce-ae20-276264355634",
                            Coach = 0,
                            Location = 0,
                            Note = "Totam excepturi est.\nAutem odit illum ut aut.\nIllum delectus repellat culpa est ratione.\nVitae dolor sed quo sequi ea.\nError ea et est dolorem vero repudiandae nesciunt.",
                            Time = new DateTime(2025, 4, 23, 16, 0, 33, 481, DateTimeKind.Unspecified).AddTicks(4923)
                        },
                        new
                        {
                            Id = 29,
                            ClientId = "b1aeda4b-5069-4bbb-8a97-00f494a2621e",
                            Coach = 0,
                            Location = 0,
                            Note = "Aut commodi pariatur aut numquam deserunt. Ab omnis qui repellat earum. Rerum minus qui voluptas et aut. Amet vitae dolorem et qui expedita amet voluptatibus suscipit et. At eligendi voluptatem excepturi vel aliquam dolor asperiores. Voluptatem et sed ullam tempore officiis nemo voluptatem quae recusandae.",
                            Time = new DateTime(2025, 3, 26, 8, 25, 12, 204, DateTimeKind.Unspecified).AddTicks(1406)
                        },
                        new
                        {
                            Id = 30,
                            ClientId = "b1aeda4b-5069-4bbb-8a97-00f494a2621e",
                            Coach = 0,
                            Location = 0,
                            Note = "Quis vero unde doloremque praesentium corrupti ad aspernatur. Quod perferendis consequatur nobis dolorem eaque nisi. Exercitationem delectus vitae.",
                            Time = new DateTime(2025, 5, 25, 6, 42, 56, 344, DateTimeKind.Unspecified).AddTicks(3824)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "AlchemyCoaching");

                    b.HasData(
                        new
                        {
                            Id = "ffebb3d9-181f-4a18-b91d-662ffc762a76",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = "1bbd113f-d37a-43b9-a050-a18c4f3a4dac",
                            Name = "Coach",
                            NormalizedName = "COACH"
                        },
                        new
                        {
                            Id = "848f20ae-f5cb-45a4-b1d3-51a85703e756",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "AlchemyCoaching");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "AlchemyCoaching");

                    b.HasData(
                        new
                        {
                            Id = "12ad74ba-befe-48fa-b301-14faa9ee817e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d5e462f5-8e6c-48da-8631-9cedb189cb5b",
                            Email = "Lawrence_Marks@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "LAWRENCE_MARKS@EMAIL.COM",
                            NormalizedUserName = "LAWRENCE_MARKS@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFynXMS1R16ajbbHkBafLI5wfZvQ377C658Tn+6YIQYCNJZKWWvCMR6pXR8Q8SFdVw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3f903519-81ce-4c85-89a2-349fe8d46262",
                            TwoFactorEnabled = false,
                            UserName = "Lawrence_Marks@email.com"
                        },
                        new
                        {
                            Id = "ebe8c31b-02bf-4e19-83bc-8736c5697039",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "55fd414d-9cda-4637-b2c4-3b9ba55aa59b",
                            Email = "Jodi91@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JODI91@EMAIL.COM",
                            NormalizedUserName = "JODI91@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBODVD+xnVqnCFDx2Hgan5SFfp079qB5shK00sdv9rKgSR5Eaj8/x32Go5P4GXFQUQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "06f7765e-8466-44cf-ae7d-d50a16d7872d",
                            TwoFactorEnabled = false,
                            UserName = "Jodi91@email.com"
                        },
                        new
                        {
                            Id = "fe217307-3574-401b-b0a2-535921d6c7f0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c72dff8f-09cd-4ae4-be2a-4e93ed176443",
                            Email = "Jane.Brekke@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JANE.BREKKE@EMAIL.COM",
                            NormalizedUserName = "JANE.BREKKE@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPBBETYXRRPx7C9jvAAvmKNaF/gbBDDnmcmpFSECd3ANLJu6jGA281pGbmtfA1PEIg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4cf235e-61ca-4dd3-83b7-7757db64f407",
                            TwoFactorEnabled = false,
                            UserName = "Jane.Brekke@email.com"
                        },
                        new
                        {
                            Id = "727be5c6-1379-46ab-b486-5ed9a2054a83",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "59f986a2-e476-4de8-a483-1e9becddbf3d",
                            Email = "Patricia.Volkman71@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATRICIA.VOLKMAN71@EMAIL.COM",
                            NormalizedUserName = "PATRICIA.VOLKMAN71@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGR8r1Nk3IByF9t66OyynhEcqIzSwNFp00d9kbX6Uy8+IXxnnq1VjVQp8YMxR0pDPg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4e6f328a-4af2-4ba7-908e-1047ca791508",
                            TwoFactorEnabled = false,
                            UserName = "Patricia.Volkman71@email.com"
                        },
                        new
                        {
                            Id = "e0e696be-4ca5-42bf-89d9-10ed98fbbc7a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "38f8371e-df45-48c9-a011-e50dbee870fb",
                            Email = "Barry_Pfannerstill@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "BARRY_PFANNERSTILL@EMAIL.COM",
                            NormalizedUserName = "BARRY_PFANNERSTILL@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKpniR9PA2MQZj+MVbANb3ieLqpQWZOwcK4jI7Igal+ybeqwIRqhSxKy4E4YiJwpTA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "faf83415-06e0-470a-9a67-5547a661ad41",
                            TwoFactorEnabled = false,
                            UserName = "Barry_Pfannerstill@email.com"
                        },
                        new
                        {
                            Id = "c5b75e07-e765-49ce-ae20-276264355634",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "886e988a-e1d5-4c47-bb9b-ed5e7c93a6f1",
                            Email = "Vivian_Zieme53@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VIVIAN_ZIEME53@EMAIL.COM",
                            NormalizedUserName = "VIVIAN_ZIEME53@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFjcxBlWt+Xvm6aaJKlpTq24ApGtk9NmEOOVDrTX/dDXbWoqAKG9cL9FclnOSTtf8w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2b7486db-6b80-462e-8202-28d69e7f489f",
                            TwoFactorEnabled = false,
                            UserName = "Vivian_Zieme53@email.com"
                        },
                        new
                        {
                            Id = "c44a61c6-ccd9-47c8-be98-d6e9f935c8b7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9e5c3b09-383f-42ea-b323-ecd7abe6dafe",
                            Email = "Erika.Treutel14@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ERIKA.TREUTEL14@EMAIL.COM",
                            NormalizedUserName = "ERIKA.TREUTEL14@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEALshadyG+mhU7pfS7e3gYgNRElF2B0RgmjrniczSKwAW0v+7AhNh1m+UTKWFbFEfg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ac90fef0-de53-4d34-8858-4cc023b6562d",
                            TwoFactorEnabled = false,
                            UserName = "Erika.Treutel14@email.com"
                        },
                        new
                        {
                            Id = "2b8d00ad-ec68-45a7-9b6e-c8f76e5dd390",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6b3ffe93-208a-4621-86e8-43e6c5cbca80",
                            Email = "Alyssa_Carroll@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALYSSA_CARROLL@EMAIL.COM",
                            NormalizedUserName = "ALYSSA_CARROLL@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJo596AJhB9unqygLZcbmS1kb63wKPN8MNsjxaVHgBNb9RG1LVRePmOhZC5rA4wKTg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6439ae89-a126-4843-b2d8-7279c56a81b7",
                            TwoFactorEnabled = false,
                            UserName = "Alyssa_Carroll@email.com"
                        },
                        new
                        {
                            Id = "1001c0f2-a1cf-4ce0-9c92-659ee13859b5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "69f66523-34d4-4105-a42b-371383786c19",
                            Email = "Marvin.OKon77@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MARVIN.OKON77@EMAIL.COM",
                            NormalizedUserName = "MARVIN.OKON77@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHChkbN5dLY4hfC25x+V/CDOFK9OVkFd0TCZ7+pa204EQN7hPYobBBUG9h3jxzS8ng==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "55fc713c-daee-4aa4-a484-2e3b88a49578",
                            TwoFactorEnabled = false,
                            UserName = "Marvin.OKon77@email.com"
                        },
                        new
                        {
                            Id = "b1aeda4b-5069-4bbb-8a97-00f494a2621e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e4e5ffb0-2448-47b2-86b0-e3ac852de726",
                            Email = "Randolph.Auer84@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "RANDOLPH.AUER84@EMAIL.COM",
                            NormalizedUserName = "RANDOLPH.AUER84@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDioGN+TeMp/y8xpcQX98o20EDfvaqYJ4k+9mnP+3x/MQnx5SsCZkDwXKgNlnmXnHQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fcb83a5c-9660-48c4-a04a-356fb55741cc",
                            TwoFactorEnabled = false,
                            UserName = "Randolph.Auer84@email.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "59412f55-40a1-4faf-8564-8322846b3dba",
                            Email = "alisonjoyforster@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALISONJOYFORSTER@GMAIL.COM",
                            NormalizedUserName = "ALISON",
                            PasswordHash = "AQAAAAIAAYagAAAAEGYU3tj1NTmmL4LwqabepMZwl44sE6CyCo5YORwlvtJE/YZMzw/SrHoqgW4RfVrtVw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a2898c5e-a1ad-4292-a383-8ddd21f39166",
                            TwoFactorEnabled = false,
                            UserName = "Alison"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "AlchemyCoaching");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "AlchemyCoaching");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "AlchemyCoaching");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "AlchemyCoaching");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
